$axure.loadCurrentPage({
  "url":"输入账号密码.html",
  "generationDate":new Date(1438937496474.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4622f30b3d2c45a789c0bb06d9f62e50",
    "type":"Axure:Page",
    "name":"输入账号密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c453976fa83b46059c9d58314beab25f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d35daa93a35d425e948376befcfb727c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"0e886be627a64c6b8656d7dd451f63ce",
          "label":"email-field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":400,
              "y":200},
            "size":{
              "width":266,
              "height":25}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"7f337ed7a48e4b60a2ceab4f993d5cda"}},
{
          "id":"b128c975c6934b14b43b7d18affb4224",
          "label":"pw-field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":400,
              "y":240},
            "size":{
              "width":266,
              "height":25}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"7f337ed7a48e4b60a2ceab4f993d5cda"}},
{
          "id":"7f337ed7a48e4b60a2ceab4f993d5cda",
          "label":"submit",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "opacity":"0.8"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":484,
              "y":275},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"688210fa1498492e9ebbaa4f9bea9335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"0.8"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":484,
                  "y":275},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If 文字于 email-field 等于 &quot;daji&quot; 和 文字于 pw-field 等于 &quot;123456&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["0e886be627a64c6b8656d7dd451f63ce"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"daji",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["b128c975c6934b14b43b7d18affb4224"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"123456",
                        "stos":[]}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 error-message to State2 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["5592939d477f4e228b2d04287133b3c2"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 游戏CG",
                      "target":{
                        "targetType":"page",
                        "url":"游戏cg.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 error-message to State1 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["5592939d477f4e228b2d04287133b3c2"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/submit_u4.png",
            "mouseOver~":"images/home/submit_u4.png"}},
{
          "id":"5592939d477f4e228b2d04287133b3c2",
          "label":"error-message",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":444,
              "y":315},
            "size":{
              "width":181,
              "height":28},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e41f936dd2c0435098a97b91a6a98b7a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9742360296a3412685e450255c04aedb",
                  "label":"",
                  "parentDynamicPanel":"5592939d477f4e228b2d04287133b3c2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Bold', 'Helvetica'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "size":{
                      "width":180,
                      "height":28},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d70a17e315b497682c9d49830894b51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5592939d477f4e228b2d04287133b3c2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Bold', 'Helvetica'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "size":{
                          "width":180,
                          "height":28},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u7.png"}}]},
{
              "id":"42eaa237c7874d1ab86337f9c75d6078",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"31186dfc76374845a6244c95047f8b1d",
                  "label":"",
                  "parentDynamicPanel":"5592939d477f4e228b2d04287133b3c2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "size":{
                      "width":180,
                      "height":28},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"441abee3334e47a4a9fe0b69f98471e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5592939d477f4e228b2d04287133b3c2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "size":{
                          "width":180,
                          "height":28},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u7.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "c453976fa83b46059c9d58314beab25f":{
      "scriptId":"u0"},
    "d35daa93a35d425e948376befcfb727c":{
      "scriptId":"u1"},
    "0e886be627a64c6b8656d7dd451f63ce":{
      "scriptId":"u2"},
    "b128c975c6934b14b43b7d18affb4224":{
      "scriptId":"u3"},
    "7f337ed7a48e4b60a2ceab4f993d5cda":{
      "scriptId":"u4"},
    "688210fa1498492e9ebbaa4f9bea9335":{
      "scriptId":"u5"},
    "5592939d477f4e228b2d04287133b3c2":{
      "scriptId":"u6"},
    "9742360296a3412685e450255c04aedb":{
      "scriptId":"u7"},
    "7d70a17e315b497682c9d49830894b51":{
      "scriptId":"u8"},
    "31186dfc76374845a6244c95047f8b1d":{
      "scriptId":"u9"},
    "441abee3334e47a4a9fe0b69f98471e4":{
      "scriptId":"u10"}}});