$axure.loadCurrentPage({
  "url":"角色列表界面.html",
  "generationDate":new Date(1438937497366.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a218b18057d0444eb883f2472d58c884",
    "type":"Axure:Page",
    "name":"角色列表界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7aed313f503544b1b2e72d8cb4cc919f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c3e461f3ed4a8290cda74be3edf8c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"1d99cabc75634e678792ba080bcae74e",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCFF},
            "location":{
              "x":58,
              "y":530},
            "size":{
              "width":80,
              "height":80},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85e0ffee18c480a8d8ec5654979cf82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF},
                "location":{
                  "x":58,
                  "y":530},
                "size":{
                  "width":80,
                  "height":80},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建角色界面",
                      "target":{
                        "targetType":"page",
                        "url":"创建角色界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/创建角色界面/返回_u4.png"}},
{
          "id":"8bac26113059455989a31c1262d1b8ad",
          "label":"Char2",
          "type":"flowShape",
          "styleType":"flowShape",
          "disabled":true,
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9933FF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFCC99},
{
                  "color":0xFFFFCC99},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":380,
              "y":70},
            "size":{
              "width":260,
              "height":490},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9933}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8c4876a700438da7dacf62f812c33d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9933FF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFCC99},
{
                      "color":0xFFFFCC99},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":380,
                  "y":70},
                "size":{
                  "width":260,
                  "height":490},
                "visible":false,
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建角色界面/char2_u17.png"}},
{
          "id":"59d67465893243b2b36bf8552059158d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x1EFFFFFF},
            "location":{
              "x":910,
              "y":430},
            "size":{
              "width":400,
              "height":400},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95cf4d335974ee79efbec8ee8877c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x1EFFFFFF},
                "location":{
                  "x":910,
                  "y":430},
                "size":{
                  "width":400,
                  "height":400},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/u6.png"}},
{
          "id":"4d4a82324dc447cc8ddbba10c626fa1f",
          "label":"技能0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":1006,
              "y":528},
            "size":{
              "width":104,
              "height":104},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d7fd79d01de451ebbd4e1211922af18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":1006,
                  "y":528},
                "size":{
                  "width":104,
                  "height":104},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/技能0_u8.png"}},
{
          "id":"a93830bacbf44036ad7bb2c8c5778be9",
          "label":"技能0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1012,
              "y":534},
            "size":{
              "width":94,
              "height":94},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da44abcdf9084d3f8d16a2fe8123d948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1012,
                  "y":534},
                "size":{
                  "width":94,
                  "height":94},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/技能0_u10.png"}},
{
          "id":"103c7a607f0542eea3a926aac6293561",
          "label":"技能0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":1036,
              "y":396},
            "size":{
              "width":74,
              "height":74},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef2eeac87204f9093841e2556deedd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":1036,
                  "y":396},
                "size":{
                  "width":74,
                  "height":74},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/技能0_u12.png"}},
{
          "id":"64f521837064481cb4faae2aab69e263",
          "label":"技能1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1042,
              "y":402},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7feea74ec18944cfac458cbe46cb0153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1042,
                  "y":402},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 职业介绍战士 向下滑动 200 ms",
                      "objectsToFades":[{
                          "objectPath":["e9d40df254a64e2bad1108933d3bb492"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"slideDown",
                              "duration":200,
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 职业介绍法师",
                      "objectsToFades":[{
                          "objectPath":["db22a2c9a9f74e0ca95a9d7d6324e546"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 Char,<br>隐藏 Char2",
                      "objectsToFades":[{
                          "objectPath":["aac502b3a53d43e1a301d3e18350802d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8bac26113059455989a31c1262d1b8ad"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/角色列表界面/技能1_u14.png"}},
{
          "id":"4e94bc01af99404abec1dc8123c8ac66",
          "label":"技能0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":956,
              "y":420},
            "size":{
              "width":74,
              "height":74},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2afaf4885041467dbe624c19c147a098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":956,
                  "y":420},
                "size":{
                  "width":74,
                  "height":74},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/技能0_u12.png"}},
{
          "id":"13c4d0fa3eaf4c5cbad3c44bd3d4468c",
          "label":"技能2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":962,
              "y":424},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14041f40114243839585f9b34a660112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":424},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 职业介绍法师 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["db22a2c9a9f74e0ca95a9d7d6324e546"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 职业介绍战士",
                      "objectsToFades":[{
                          "objectPath":["e9d40df254a64e2bad1108933d3bb492"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 Char2,<br>隐藏 Char",
                      "objectsToFades":[{
                          "objectPath":["8bac26113059455989a31c1262d1b8ad"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aac502b3a53d43e1a301d3e18350802d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/角色列表界面/技能1_u14.png"}},
{
          "id":"deb19d065837477babb96217399c7d0d",
          "label":"技能0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"16px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":902,
              "y":480},
            "size":{
              "width":74,
              "height":74},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b78dc9f6074ffbbbb37de2720ec31b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"16px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":902,
                  "y":480},
                "size":{
                  "width":74,
                  "height":74},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/技能0_u12.png"}},
{
          "id":"87ed1c56e724449786a3a42d8370433a",
          "label":"技能0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":874,
              "y":560},
            "size":{
              "width":74,
              "height":74},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b580f0dbb3d4d0cb000a92078ab3077",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":874,
                  "y":560},
                "size":{
                  "width":74,
                  "height":74},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色列表界面/技能0_u12.png"}},
{
          "id":"405e6fae9d5247fab9d64098cb6b784c",
          "label":"技能3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":908,
              "y":486},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656f445bc14646edb2f605222dd9eec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":908,
                  "y":486},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建角色界面",
                      "target":{
                        "targetType":"page",
                        "url":"创建角色界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/角色列表界面/技能1_u14.png"}},
{
          "id":"bfb8d402b2744dd79a91b295fb51aef1",
          "label":"技能4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":880,
              "y":564},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2395fbae654745a7cc74839243c5e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":880,
                  "y":564},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建角色界面",
                      "target":{
                        "targetType":"page",
                        "url":"创建角色界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/角色列表界面/技能1_u14.png"}},
{
          "id":"e9d40df254a64e2bad1108933d3bb492",
          "label":"职业介绍战士",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":936,
              "y":332},
            "size":{
              "width":200,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"29443c88e8ce4d2cbaf29d15ceefe250",
              "label":"战士介绍",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e20d915f30bb44a8b2f14273e39f9651",
                  "label":"",
                  "parentDynamicPanel":"e9d40df254a64e2bad1108933d3bb492",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":60},
                    "borderWidth":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"611d29e61325485d95c7aa9699111a23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e9d40df254a64e2bad1108933d3bb492",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":60},
                        "borderWidth":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/角色列表界面/u29.png"}},
{
                  "id":"96a836fbd5ea4d9bb7be192628ace42d",
                  "label":"",
                  "parentDynamicPanel":"e9d40df254a64e2bad1108933d3bb492",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":10,
                      "y":13},
                    "size":{
                      "width":180,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fd30061d3704518a47f945bae7dc99b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e9d40df254a64e2bad1108933d3bb492",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":10,
                          "y":13},
                        "size":{
                          "width":180,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"db22a2c9a9f74e0ca95a9d7d6324e546",
          "label":"职业介绍法师",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":936,
              "y":332},
            "size":{
              "width":200,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"bff39a1fdb834c0ba8c1083d5456cefc",
              "label":"法师介绍",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6dc37f86f1a04db2b8fc610e57b1781a",
                  "label":"",
                  "parentDynamicPanel":"db22a2c9a9f74e0ca95a9d7d6324e546",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":60},
                    "borderWidth":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0abb454ed954f1d9b8008587aa476ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"db22a2c9a9f74e0ca95a9d7d6324e546",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":60},
                        "borderWidth":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/角色列表界面/u29.png"}},
{
                  "id":"5a78a5067fc04497969bfc11df65f439",
                  "label":"",
                  "parentDynamicPanel":"db22a2c9a9f74e0ca95a9d7d6324e546",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":10,
                      "y":13},
                    "size":{
                      "width":180,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85cc95def2624414a1f237b4164a8e42",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"db22a2c9a9f74e0ca95a9d7d6324e546",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":10,
                          "y":13},
                        "size":{
                          "width":180,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"aac502b3a53d43e1a301d3e18350802d",
          "label":"Char",
          "type":"flowShape",
          "styleType":"flowShape",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9933FF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":380,
              "y":70},
            "size":{
              "width":260,
              "height":490},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"992abfbe620a404399fb76aef1595f1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9933FF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":380,
                  "y":70},
                "size":{
                  "width":260,
                  "height":490},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建角色界面/char1_u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7aed313f503544b1b2e72d8cb4cc919f":{
      "scriptId":"u0"},
    "31c3e461f3ed4a8290cda74be3edf8c8":{
      "scriptId":"u1"},
    "1d99cabc75634e678792ba080bcae74e":{
      "scriptId":"u2"},
    "d85e0ffee18c480a8d8ec5654979cf82":{
      "scriptId":"u3"},
    "8bac26113059455989a31c1262d1b8ad":{
      "scriptId":"u4"},
    "ac8c4876a700438da7dacf62f812c33d":{
      "scriptId":"u5"},
    "59d67465893243b2b36bf8552059158d":{
      "scriptId":"u6"},
    "a95cf4d335974ee79efbec8ee8877c44":{
      "scriptId":"u7"},
    "4d4a82324dc447cc8ddbba10c626fa1f":{
      "scriptId":"u8"},
    "6d7fd79d01de451ebbd4e1211922af18":{
      "scriptId":"u9"},
    "a93830bacbf44036ad7bb2c8c5778be9":{
      "scriptId":"u10"},
    "da44abcdf9084d3f8d16a2fe8123d948":{
      "scriptId":"u11"},
    "103c7a607f0542eea3a926aac6293561":{
      "scriptId":"u12"},
    "cef2eeac87204f9093841e2556deedd2":{
      "scriptId":"u13"},
    "64f521837064481cb4faae2aab69e263":{
      "scriptId":"u14"},
    "7feea74ec18944cfac458cbe46cb0153":{
      "scriptId":"u15"},
    "4e94bc01af99404abec1dc8123c8ac66":{
      "scriptId":"u16"},
    "2afaf4885041467dbe624c19c147a098":{
      "scriptId":"u17"},
    "13c4d0fa3eaf4c5cbad3c44bd3d4468c":{
      "scriptId":"u18"},
    "14041f40114243839585f9b34a660112":{
      "scriptId":"u19"},
    "deb19d065837477babb96217399c7d0d":{
      "scriptId":"u20"},
    "28b78dc9f6074ffbbbb37de2720ec31b":{
      "scriptId":"u21"},
    "87ed1c56e724449786a3a42d8370433a":{
      "scriptId":"u22"},
    "3b580f0dbb3d4d0cb000a92078ab3077":{
      "scriptId":"u23"},
    "405e6fae9d5247fab9d64098cb6b784c":{
      "scriptId":"u24"},
    "656f445bc14646edb2f605222dd9eec3":{
      "scriptId":"u25"},
    "bfb8d402b2744dd79a91b295fb51aef1":{
      "scriptId":"u26"},
    "3b2395fbae654745a7cc74839243c5e6":{
      "scriptId":"u27"},
    "e9d40df254a64e2bad1108933d3bb492":{
      "scriptId":"u28"},
    "e20d915f30bb44a8b2f14273e39f9651":{
      "scriptId":"u29"},
    "611d29e61325485d95c7aa9699111a23":{
      "scriptId":"u30"},
    "96a836fbd5ea4d9bb7be192628ace42d":{
      "scriptId":"u31"},
    "2fd30061d3704518a47f945bae7dc99b":{
      "scriptId":"u32"},
    "db22a2c9a9f74e0ca95a9d7d6324e546":{
      "scriptId":"u33"},
    "6dc37f86f1a04db2b8fc610e57b1781a":{
      "scriptId":"u34"},
    "e0abb454ed954f1d9b8008587aa476ad":{
      "scriptId":"u35"},
    "5a78a5067fc04497969bfc11df65f439":{
      "scriptId":"u36"},
    "85cc95def2624414a1f237b4164a8e42":{
      "scriptId":"u37"},
    "aac502b3a53d43e1a301d3e18350802d":{
      "scriptId":"u38"},
    "992abfbe620a404399fb76aef1595f1d":{
      "scriptId":"u39"}}});