$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1438937496210.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e210f726f0343af90cc4ee67bf3d476",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e34d88d74cae4fa2bdaa562b2665309a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58be277146164739990c6b2e1d46671f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"f23b2abc4b3143e49d15ab44fa5cb23d",
          "label":"email-field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":400,
              "y":200},
            "size":{
              "width":266,
              "height":25}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"a707e923dde2489da93067245ce13399"}},
{
          "id":"555604c7e6834f11a8d0131886391da7",
          "label":"pw-field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":400,
              "y":240},
            "size":{
              "width":266,
              "height":25}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"a707e923dde2489da93067245ce13399"}},
{
          "id":"a707e923dde2489da93067245ce13399",
          "label":"submit",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "opacity":"0.8"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":484,
              "y":275},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5a21857c8e04e5aa4e38c436512e256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"0.8"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":484,
                  "y":275},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If 文字于 email-field 等于 &quot;daji&quot; 和 文字于 pw-field 等于 &quot;123456&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["f23b2abc4b3143e49d15ab44fa5cb23d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"daji",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["555604c7e6834f11a8d0131886391da7"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"123456",
                        "stos":[]}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 error-message to State2 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["e88849fa672849aaa76c3899563aca9f"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 游戏CG",
                      "target":{
                        "targetType":"page",
                        "url":"游戏cg.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 error-message to State1 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["e88849fa672849aaa76c3899563aca9f"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/submit_u4.png",
            "mouseOver~":"images/home/submit_u4.png"}},
{
          "id":"e88849fa672849aaa76c3899563aca9f",
          "label":"error-message",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":444,
              "y":315},
            "size":{
              "width":181,
              "height":28},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e3413f15b97e44cebf36440692ae292e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ecc4a9df59054d2b87933e104b956981",
                  "label":"",
                  "parentDynamicPanel":"e88849fa672849aaa76c3899563aca9f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Bold', 'Helvetica'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "size":{
                      "width":180,
                      "height":28},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"360366354c504ef2a4520151ef5f40ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e88849fa672849aaa76c3899563aca9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Bold', 'Helvetica'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "size":{
                          "width":180,
                          "height":28},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u7.png"}}]},
{
              "id":"1d12bf00ea4d47ce9a766b7866ae8f15",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9954d1cd732f4a07b6939abfea1b20d2",
                  "label":"",
                  "parentDynamicPanel":"e88849fa672849aaa76c3899563aca9f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "size":{
                      "width":180,
                      "height":28},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a7ddc9f70854471a8163b48759a099e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e88849fa672849aaa76c3899563aca9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "size":{
                          "width":180,
                          "height":28},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u7.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "e34d88d74cae4fa2bdaa562b2665309a":{
      "scriptId":"u0"},
    "58be277146164739990c6b2e1d46671f":{
      "scriptId":"u1"},
    "f23b2abc4b3143e49d15ab44fa5cb23d":{
      "scriptId":"u2"},
    "555604c7e6834f11a8d0131886391da7":{
      "scriptId":"u3"},
    "a707e923dde2489da93067245ce13399":{
      "scriptId":"u4"},
    "f5a21857c8e04e5aa4e38c436512e256":{
      "scriptId":"u5"},
    "e88849fa672849aaa76c3899563aca9f":{
      "scriptId":"u6"},
    "ecc4a9df59054d2b87933e104b956981":{
      "scriptId":"u7"},
    "360366354c504ef2a4520151ef5f40ea":{
      "scriptId":"u8"},
    "9954d1cd732f4a07b6939abfea1b20d2":{
      "scriptId":"u9"},
    "6a7ddc9f70854471a8163b48759a099e":{
      "scriptId":"u10"}}});